### ISSUE TITLE
Support for windows?

### ISSUE THREAD

**Issue by Gitterman69** [AiuniAI/Unique3D#10]
How do i installe/run this under windows?

**Comment by jtydhr88** [comment]
see https://github.com/AiuniAI/Unique3D/issues/15

**Comment by Gitterman69** [comment]
Those steps failed here.  I will wait for the official Windows support they have on the to do list.

**Comment by jtydhr88** [comment]
please share the errors happen on your end.
And I believe they choose mine as the resolution, since it is mentioned in README now.

**Comment by SoftologyPro** [comment]
He was posting for me.
My steps and stats in your original Windows post.
https://github.com/AiuniAI/Unique3D/issues/15#issuecomment-2157407776
