### ISSUE TITLE
6-views

### ISSUE THREAD

**Issue by Dan1900** [AiuniAI/Unique3D#106]
I want to use 6-views.But I get this error: The view direction is not correct. cos_angles.mean()=0.2374737560749054
If I use 6-views,What should I pay attention to?Thank you!

**Comment by Dan1900** [comment]
It seems 6-views reconstruction inferior to 4-views.
![企业微信截图_17271637709395](https://github.com/user-attachments/assets/5a325fa3-8d8b-4e60-b113-47e0f953e5bd)
![企业微信截图_17271637909934](https://github.com/user-attachments/assets/9ab9df06-93a6-423c-9501-27eb8f8d041c)

**Comment by josepmy** [comment]
You need the data trained for 6 views too

**Comment by Dan1900** [comment]
> You need the data trained for 6 views too and currently is only 4 viewa

Thank you for your reply.I'll try to  use other project to producing 6 views,then use this projects for reconstrution.
