### ISSUE TITLE
一些失败的case

### ISSUE THREAD

**Issue by LaFeuilleMorte** [AiuniAI/Unique3D#11]
Hi，感谢开源这么牛的作品。不过我在试用的时候发现会有一些很简单的生成也会失败：
<img width="1020" alt="Screenshot 2024-06-06 at 10 25 57" src="https://github.com/AiuniAI/Unique3D/assets/43473814/073de36d-5f16-40c1-a188-8237665f017f">

这个椅子是正面的照片，但是出来的mesh完全collapse掉了

**Comment by wukailu** [comment]
是的，我们接下来会release v1.1 版本，通过对于法向预测的增强和加入深度预测来降低崩掉的概率（特别是各种物体）
