### ISSUE TITLE
Training data filtering strategy

### ISSUE THREAD

**Issue by lorenmt** [AiuniAI/Unique3D#14]
Dear Authors,

Congratulations on the release of your great work. I am wondering whether you have tried training the model on the unfiltered 800k Objaverse in your early exploration of the project? If so, dropping 800k to 50k and still achieving a better performance clearly highlights the importance of training data quality. Considering that, would that be possible for you to kindly release the 50k object ids / filtering code which I believe would be a great contribution to the 3Dgen community.

**Comment by wukailu** [comment]
Due to resource constraints, we did not train the full 800K dataset before. After that we will try to filter and train on the whole dataset.
