### ISSUE TITLE
auto not supported. Supported strategies are: balanced

### ISSUE THREAD

**Issue by JinGuKon** [AiuniAI/Unique3D#24]
https://github.com/AiuniAI/Unique3D/blob/56b98f641f93b84507de05442e6bff561a11282f/scripts/sd_model_zoo.py#L68

https://github.com/huggingface/diffusers/blob/f96e4a16adb4c31bab4c0a3d0d145ed2b086ecb0/src/diffusers/pipelines/pipeline_utils.py#L95C1-L95C36

auto not supported. Supported strategies are: balanced

**Comment by Aiunii** [comment]
Hey! 
Welcome to 4D digital art creation universe—— Aiuni.

🤖First, join our community by:
 https://discord.gg/aiuni

🦄️Then you will get the invitation code at “getting-started” channel.

Start your creative journey and have fun!🌟

**Comment by Aiunii** [comment]
Hey! 
Welcome to 4D digital art creation universe—— Aiuni.

🤖First, join our community by:
 https://discord.gg/aiuni

🦄️Then you will get the invitation code at “getting-started” channel.

Start your creative journey and have fun!🌟

**Comment by jtydhr88** [comment]
hi, this is because you install diffusers greater than 0.28, this code of repo depends on diffusers==0.27.2
