### ISSUE TITLE
Getting numpy version error when try to run.

### ISSUE THREAD

**Issue by bianyunzhi95** [AiuniAI/Unique3D#30]
On ubuntu 22.04 with cuda 12.1, after installation, gradio app isn't running with following output.
`
python app/gradio_local.py --port 7860

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.0.0 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.
`

**Comment by JinGuKon** [comment]
downgrade pytorch version

**Comment by bianyunzhi95** [comment]
Could you tell me what version you are using exactly please?

**Comment by JinGuKon** [comment]
> Could you tell me what version you are using exactly please?

torch 2.1.0.post2
numpy 1.24.4
