### ISSUE TITLE
About GPU compatible support.

### ISSUE THREAD

**Issue by Colezwhy** [AiuniAI/Unique3D#33]
Hi, thank you very much for your great work!
But I wonder if there is a compatible environment to perform Unique3D on RTX3090 GPUs, since I got many errors when trying to install some packages following the readme.

**Comment by Lektro9** [comment]
I have it working under Windows docker desktop with a 3090. The errors you are getting are probably tied to mismatching pytorch or cuda versions. But it would help a lot if you posted some error logs as we would be guessing what went wrong.

**Comment by Colezwhy** [comment]
> I have it working under Windows docker desktop with a 3090. The errors you are getting are probably tied to mismatching pytorch or cuda versions. But it would help a lot if you posted some error logs as we would be guessing what went wrong.

Thank you, I have resolved it with other versions of cuda and pytorch support.
