### ISSUE TITLE
About input image simple process

### ISSUE THREAD

**Issue by Yzhbuaa** [AiuniAI/Unique3D#36]
Hello,

Thank you for the excellent work. I have a question regarding the preprocessing step. Could you please explain why the input image needs to be cropped before being fed into the pipeline? Is this related to how the model was trained?

I experimented with using the original, uncropped image, but the generated results were not as good. Specifically, when feeding the original image into the pipeline, the side views often have a 'long tail' behind the object.
![image](https://github.com/AiuniAI/Unique3D/assets/44798666/630c7c9a-8d9b-49e1-9848-788158776463)

Thank you for your assistance.

**Comment by wukailu** [comment]
Because the data is scaled into the [-1,1] box during training, implicitly the model learns that either the left and right will top the box or the front and back will top it.
