### ISSUE TITLE
Why can ExplicitTarget Optimization solve the Multi-view Inconsistency issue?

### ISSUE THREAD

**Issue by YuQiao0303** [AiuniAI/Unique3D#44]
Hi, authors. Thank you for this amazing work!

I'm a bit confused by how unique3d  solves the multi-view inconsistency issue. 

The explicit target looks like finding the color for each 3D point by the weighted sum of corresponding pixels of visible views. Is my understanding correct? Why would this solve the multiview inconsistency issue? It still uses different views, and if the views are inconsistent, why wouldn't it still influence the generated mesh?

**Comment by wukailu** [comment]
When multiple viewpoints are inconsistent, there is no theoretically optimal solution per se, so it's just a matter of some modifications that allow the iterations to converge to a solution that is good relative to humans. Wavy imperfections tend to appear when the same surface is seen from different viewpoints and in different directions (as this minimises the loss). However, such imperfections are not desired, so averaging the results from different viewpoints ensures that the final surface is relatively smooth.

**Comment by YuQiao0303** [comment]
> When multiple viewpoints are inconsistent, there is no theoretically optimal solution per se, so it's just a matter of some modifications that allow the iterations to converge to a solution that is good relative to humans. Wavy imperfections tend to appear when the same surface is seen from different viewpoints and in different directions (as this minimises the loss). However, such imperfections are not desired, so averaging the results from different viewpoints ensures that the final surface is relatively smooth.

I see. Thank you!
