### ISSUE TITLE
About the pipeline in the paper.

### ISSUE THREAD

**Issue by Colezwhy** [AiuniAI/Unique3D#49]
Hi dear authors,
Thank you for your great work, but I have some problems on the whole pipeline of the paper.
In the figure of pipeline, there is a '*N' when generating multi-view images and upscaling, what does that mean?
Like use Multi-view Diffusion models and take its results and then feed to the Multi-view Diffusion again for N times?
![image](https://github.com/AiuniAI/Unique3D/assets/96565109/0b547804-948f-445f-a505-7b9c2d4047d0)

**Comment by wukailu** [comment]
This means diffusion operation because the denoising process performs multiple inference on the unet model and N is the number of diffusion steps.

**Comment by Colezwhy** [comment]
> This means diffusion operation because the denoising process performs multiple inference on the unet model and N is the number of diffusion steps.

Thank you for your reply.
