### ISSUE TITLE
只能使用gradio进行在线部署？

### ISSUE THREAD

**Issue by bc129697** [AiuniAI/Unique3D#52]
只能使用gradio进行在线部署进行推理？能不能关闭gradio，只在本地进行推理？

**Comment by jtydhr88** [comment]
理论上当然可以，看有没有人贡献代码了

**Comment by wukailu** [comment]
因为初始化环境的时间很长（加载各种模型），所以一般建议启动gradio后挂在后台，然后使用 gradio-client 进行 API 调用，这样效率会高很多。
