### ISSUE TITLE
多视图生成3D时报错

### ISSUE THREAD

**Issue by sp1cae** [AiuniAI/Unique3D#54]
多视图和主视图都是项目生成的，有时会出现下面的错误：
assert cos_angles.mean() < 0, f"The view direction is not correct. cos_angles.mean()={cos_angles.mean()}"
AssertionError: The view direction is not correct. cos_angles.mean()=0.062265731394290924

**Comment by jtydhr88** [comment]
换seed

**Comment by wukailu** [comment]
换seed，这个是因为代码里有一行 assert 检查最后一步前所有面的朝向（你也可以强行删掉这个assert），如果存在一些面是错误的方向，说明这个模型大概率迭代崩掉了

**Comment by josepmy** [comment]
I have the same issue, any solution? 
@wukailu Did you mean to remove the line or control this assertion line if there are some faces that are facing the wrong direction checking the error? I think can add a tolerance of 0.05. Make sense?

    # find invalid faces
    cos_angles = (faces_normals * view_direction).sum(dim=1)
    assert cos_angles.mean() < 0.05, f"The view direction is not correct. cos_angles.mean()={cos_angles.mean()}"
    selected_faces = unique_faces[cos_angles < -eps]

**Comment by j71200** [comment]
In my case, I downgrade nvdiffrast to v0.3.1 to solve it.

```
git clone https://github.com/NVlabs/nvdiffrast.git
cd nvdiffrast
git checkout v0.3.1
pip install -e .
```
