### ISSUE TITLE
quality issues

### ISSUE THREAD

**Issue by KenNavarro730** [AiuniAI/Unique3D#61]
Since nvdiffrast didnt work on my machine I tried to use the old pytorch3d version to do everything. Replacing recon.py, refine.py and project_mesh.py as necessary to make pytorch3d render. However the results I am getting are much worse, even with doing what the other person in this issues thread of making the resolution In project_mesh.py higher (I changed every H,W,resolution variable to 8192 so maybe its the resolution of the input photo I'm using? Checking that next), is this issue likely arising from nvdiffrast somehow producing much better quality 3d renderings? Or is it something else that the online demo is doing I am not aware of?

**Comment by KenNavarro730** [comment]
Also also, here is an example of the quality difference. 
![Uploading Screenshot 2024-07-08 at 4.03.47 PM.png…]()

**Comment by KenNavarro730** [comment]
Here example of quality difference
<img width="1554" alt="Screenshot 2024-07-08 at 4 03 47 PM" src="https://github.com/AiuniAI/Unique3D/assets/97278845/682e957f-5c46-4305-bf48-70aed02353d6">

<img width="1554" alt="Screenshot 2024-07-08 at 4 03 54 PM" src="https://github.com/AiuniAI/Unique3D/assets/97278845/baaa3cd8-1f04-4641-a24e-b8c3d872055e">

**Comment by wukailu** [comment]
As far as we know, Pytorch3d, for its own reasons, may not render the image correctly in some cases (e.g. when pytorch3d itself raises a warning about max_faces_per_bins). This can lead to miscalculations in the final result. Meanwhile, pytorch3d, despite having similar rendering results, is not identical to the nvdiffrast rendering, especially at the edges.
