### ISSUE TITLE
是否会有多图像生成模型的支持,单图像生成后某些位置生成效果很差

### ISSUE THREAD

**Issue by Hans-Wu-cn** [AiuniAI/Unique3D#69]
是否会有多图像生成模型的支持,单图像生成后某些位置生成效果很差
![image](https://github.com/user-attachments/assets/a7c49678-4aa0-45a2-ba97-9a9084125d33)

**Comment by wukailu** [comment]
我们可能在之后的新的三维生成模型研发中，训练时考虑对于多视图输入的支持。我们也关注到了多视图输入是许多用户的需求。
