### ISSUE TITLE
真人照片关于脸部

### ISSUE THREAD

**Issue by wing158** [AiuniAI/Unique3D#7]
真人脸部反建是否有参数可选，头部放大1.2-1.3，鼻子现在过尖,可提供深度平缓压平一些的参数可选？

**Comment by wukailu** [comment]
1. 因为目前算法基本假设是正交视角下正视图一定和用户给出图像完全一致，所以没法在3D生成层面放大用户头部。建议PhotoShop放大用户头部后再传入我们的算法。
2. 目前gradio仅作基础功能展示。之后我们会实现对应的功能丰富的 comfyui 组件，提供直观且高度可控的功能组合。
3. 如果要压低鼻尖，把 https://github.com/AiuniAI/Unique3D/blob/bd054f79158f77f1b6b16817e8780191c9ebb127/scripts/multiview_inference.py#L73 中 guidance_scale 调低能起到一定效果。
