### ISSUE TITLE
 Can he generate a panoramic image based on indoor images

### ISSUE THREAD

**Issue by libai-lab** [AiuniAI/Unique3D#78]
Can he generate a panoramic image based on indoor images

**Comment by wukailu** [comment]
For now, for the ISOMER reconstruction part is theoretically possible for indoor scene reconstruction. But currently the model in the previous multi-view generation section does not use any indoor data for multi-view training. If the indoor data is used to train the multiview generation model instead, it is possible that it can be applied to indoor generation.
